version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: carlos
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: topicos
    ports:
      - "5433:5432"   # Tu máquina:5433 → Contenedor:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: carlos
      DB_PASSWORD: 12345678
      DB_NAME: topicos
      DB_PORT: 5432   # ⚠️ Internamente sigue siendo 5432
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: npm run dev:reset

volumes:
  pgdata:
